Added Documentation for Trucker Job
xSisyphusx/Documentation pull request #3
Opened 2024-07-17 10:02 UTC by Taurusgirl252

Added documentation for truck job

2024-07-17 21:51 UTC, xSisyphusx requested changes
This is okay, but I need the language to be a little better.  Please see the review points below and resubmit the PR when completed.

2024-07-17 21:51 UTC, xSisyphusx commented on job/trucker-job.md
> +- Wait for about 5 minutes and a route will be available and click on view route and select your route
Please use exact times not "about"

2024-07-17 21:51 UTC, xSisyphusx commented on job/trucker-job.md
> +> As a Trucker, your primary goal as a trucker is to transport goods to various destinations safe as possible; as This role requires a strong attention to detail, excellent driving skills, and a comm
Clean up the language here a bit. "As a Trucker, your primary goal as a trucker" is a bit redundant.

2024-07-17 21:51 UTC, xSisyphusx commented on job/trucker-job.md
> +- Drop off trailer at another location.
Be more specific here please

2024-07-17 21:51 UTC, xSisyphusx commented on job/trucker-job.md
> +- That's it, you now know how to drive a big rig. Great Job!
This is not necessary

2024-07-17 21:52 UTC, Taurusgirl252 commented on job/trucker-job.md
> +> As a Trucker, your primary goal as a trucker is to transport goods to various destinations safe as possible; as This role requires a strong attention to detail, excellent driving skills, and a comm
Roger that will do.

2024-07-17 23:26 UTC, Taurusgirl252 commented on job/trucker-job.md
> +- Wait for about 5 minutes and a route will be available and click on view route and select your route
Roger going back into it right now.

2024-07-18 00:02 UTC, Taurusgirl252 commented on job/trucker-job.md
> +- Wait for about 5 minutes and a route will be available and click on view route and select your route
I'm still new at this but I don't mind helping where it is needed. Thank you for the advice!

2024-08-06 07:47 UTC, merged